# Generated by Django 6.0.6 on 2026-07-22 09:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SGI',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant')),
                ('nom', models.CharField(max_length=255, verbose_name='Nom')),
                ('code_sgi', models.CharField(db_index=True, help_text='Code réglementaire unique attribué par le CREPMF.', max_length=20, unique=True, verbose_name='Code SGI')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='sgi/logos/', verbose_name='Logo')),
                ('est_active', models.BooleanField(default=True, help_text='Une SGI désactivée ne peut plus recevoir de nouveaux dossiers.', verbose_name='Active')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
            ],
            options={
                'verbose_name': 'SGI',
                'verbose_name_plural': 'SGI',
                'ordering': ['nom'],
            },
        ),
    ]
