# Generated by Django 6.0.6 on 2026-08-10 15:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConventionTarifaire',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant')),
                ('titre', models.CharField(blank=True, help_text="Intitulé de la convention tel qu'affiché à l'investisseur.", max_length=255, verbose_name='Titre')),
                ('fichier_pdf', models.FileField(blank=True, help_text='Document PDF de la convention tarifaire en vigueur.', upload_to='sgi/conventions/', verbose_name='Fichier PDF')),
                ('date_publication', models.DateTimeField(auto_now_add=True, verbose_name='Date de publication')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('sgi', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='convention', to='sgi.sgi', verbose_name='SGI')),
            ],
            options={
                'verbose_name': 'Convention tarifaire',
                'verbose_name_plural': 'Conventions tarifaires',
            },
        ),
        migrations.CreateModel(
            name='InformationPresentation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant')),
                ('contenu', models.TextField(blank=True, help_text='Texte de présentation de la SGI pour les investisseurs.', verbose_name='Contenu marketing')),
                ('date_publication', models.DateTimeField(auto_now_add=True, verbose_name='Date de publication')),
                ('sgi', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='presentation', to='sgi.sgi', verbose_name='SGI')),
            ],
            options={
                'verbose_name': 'Information de présentation',
                'verbose_name_plural': 'Informations de présentation',
            },
        ),
    ]
