# Generated by Django 6.0.6 on 2026-08-16 06:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgi', '0002_conventiontarifaire_informationpresentation'),
    ]

    operations = [
        migrations.AddField(
            model_name='informationpresentation',
            name='adresse',
            field=models.CharField(blank=True, max_length=255, verbose_name='Adresse'),
        ),
        migrations.AddField(
            model_name='informationpresentation',
            name='ancrage_regional',
            field=models.TextField(blank=True, verbose_name='Ancrage régional'),
        ),
        migrations.AddField(
            model_name='informationpresentation',
            name='autorite_agrement',
            field=models.CharField(blank=True, default='AMF-UEMOA (ex-CREPMF)', max_length=100, verbose_name="Autorité d'agrément"),
        ),
        migrations.AddField(
            model_name='informationpresentation',
            name='capital_social',
            field=models.CharField(blank=True, max_length=100, verbose_name='Capital social'),
        ),
        migrations.AddField(
            model_name='informationpresentation',
            name='date_agrement',
            field=models.DateField(blank=True, null=True, verbose_name="Date d'agrément"),
        ),
        migrations.AddField(
            model_name='informationpresentation',
            name='date_creation_societe',
            field=models.DateField(blank=True, null=True, verbose_name='Date de création'),
        ),
        migrations.AddField(
            model_name='informationpresentation',
            name='email_contact',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email de contact'),
        ),
        migrations.AddField(
            model_name='informationpresentation',
            name='forme_sociale',
            field=models.CharField(blank=True, max_length=50, verbose_name='Forme sociale'),
        ),
        migrations.AddField(
            model_name='informationpresentation',
            name='mission',
            field=models.TextField(blank=True, verbose_name='Mission'),
        ),
        migrations.AddField(
            model_name='informationpresentation',
            name='numero_agrement',
            field=models.CharField(blank=True, max_length=100, verbose_name="Numéro d'agrément"),
        ),
        migrations.AddField(
            model_name='informationpresentation',
            name='site_web',
            field=models.URLField(blank=True, verbose_name='Site web'),
        ),
        migrations.AddField(
            model_name='informationpresentation',
            name='telephone',
            field=models.CharField(blank=True, max_length=30, verbose_name='Téléphone'),
        ),
        migrations.AddField(
            model_name='informationpresentation',
            name='vision',
            field=models.TextField(blank=True, verbose_name='Vision'),
        ),
        migrations.AlterField(
            model_name='informationpresentation',
            name='contenu',
            field=models.TextField(blank=True, help_text='Ancien texte libre, conservé à titre de récupération.', verbose_name='Contenu marketing (historique)'),
        ),
        migrations.AlterField(
            model_name='informationpresentation',
            name='date_publication',
            field=models.DateTimeField(auto_now=True, verbose_name='Date de publication'),
        ),
        migrations.CreateModel(
            name='ActivitePresentation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('ordre', models.PositiveSmallIntegerField(default=0, verbose_name='Ordre')),
                ('presentation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activites', to='sgi.informationpresentation', verbose_name='Présentation')),
            ],
            options={
                'verbose_name': 'Activité présentée',
                'verbose_name_plural': 'Activités présentées',
                'ordering': ['ordre', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MembreEquipe',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom')),
                ('fonction', models.CharField(blank=True, max_length=200, verbose_name='Fonction')),
                ('ordre', models.PositiveSmallIntegerField(default=0, verbose_name='Ordre')),
                ('presentation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membres', to='sgi.informationpresentation', verbose_name='Présentation')),
            ],
            options={
                'verbose_name': "Membre de l'équipe",
                'verbose_name_plural': "Membres de l'équipe",
                'ordering': ['ordre', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ReferencePresentation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre')),
                ('annee', models.CharField(blank=True, max_length=20, verbose_name='Année')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('ordre', models.PositiveSmallIntegerField(default=0, verbose_name='Ordre')),
                ('presentation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references', to='sgi.informationpresentation', verbose_name='Présentation')),
            ],
            options={
                'verbose_name': 'Référence présentée',
                'verbose_name_plural': 'Références présentées',
                'ordering': ['ordre', 'id'],
            },
        ),
    ]
