# Generated by Django 6.0.6 on 2026-08-16 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgi', '0003_informationpresentation_adresse_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informationpresentation',
            name='autorite_agrement',
            field=models.CharField(blank=True, help_text='Ex : AMF-UEMOA (ex-CREPMF) — rappelée par défaut côté affichage.', max_length=100, verbose_name="Autorité d'agrément"),
        ),
    ]
