# Generated by Django 6.0.6 on 2026-09-09 01:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgi', '0004_alter_informationpresentation_autorite_agrement'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigDepotMinimum',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant')),
                ('exige_depot', models.BooleanField(default=False, help_text="Active l'obligation de dépôt minimum après validation : le dossier ne devient ACTIF qu'après approbation de la preuve.", verbose_name='Dépôt exigé')),
                ('montant_depot_min', models.DecimalField(decimal_places=0, default=0, help_text="Montant en francs CFA exigé. Ignoré si le dépôt n'est pas exigé.", max_digits=14, verbose_name='Montant minimum (FCFA)')),
                ('instructions', models.TextField(blank=True, help_text="Modalités affichées à l'investisseur (numéro, procédure…).", verbose_name='Instructions de paiement')),
                ('methodes_acceptees', models.JSONField(default=list, help_text='Liste des codes `MethodePaiement` acceptés (ex: ["ORANGE_MONEY", "WAVE"]).', verbose_name='Méthodes acceptées')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('sgi', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config_depot', to='sgi.sgi', verbose_name='SGI')),
            ],
            options={
                'verbose_name': 'Configuration de dépôt minimum',
                'verbose_name_plural': 'Configurations de dépôt minimum',
            },
        ),
    ]
