# Generated by Django 6.0.6 on 2026-08-20 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlocAccueil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('HERO', 'Accroche principale'), ('REASSURANCE', 'Bandeau de réassurance'), ('CHIFFRES', 'Chiffres clés et partenaires'), ('ETAPES', 'Comment ça marche'), ('SECURITE', 'Sécurité et conformité'), ('TEMOIGNAGES', 'Témoignages'), ('FAQ', 'Questions fréquentes'), ('APPEL_ACTION', "Appel à l'action final")], db_index=True, max_length=30, unique=True, verbose_name='Type de bloc')),
                ('titre', models.CharField(blank=True, max_length=200, verbose_name='Titre')),
                ('contenu', models.JSONField(blank=True, default=dict, help_text='Structure propre au type de bloc (voir serializers.py).', verbose_name='Contenu structuré')),
                ('image', models.ImageField(blank=True, null=True, upload_to='accueil/', verbose_name='Image')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('date_publication', models.DateTimeField(blank=True, help_text='Renseignée à la première publication (brouillon → public).', null=True, verbose_name='Date de publication')),
                ('date_maj', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
            ],
            options={
                'verbose_name': "Bloc de la page d'accueil",
                'verbose_name_plural': "Blocs de la page d'accueil",
                'ordering': ['ordre', 'type'],
            },
        ),
    ]
