"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import sys
from pathlib import Path
from datetime import timedelta

from decouple import Csv, config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Aucune valeur par défaut : l'absence de DJANGO_SECRET_KEY doit faire
# échouer le démarrage plutôt que de laisser fuiter une clé « insecure »
# en production.
SECRET_KEY = config("DJANGO_SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
# Défaut à False : oublier la variable d'env ne doit jamais activer le
# mode debug en production.
DEBUG = config("DJANGO_DEBUG", default=False, cast=bool)

# Détecte si on est dans une exécution de tests (manage.py test).
EXECUTION_TESTS = "test" in sys.argv

# Phase de build d'image (collectstatic au Dockerfile) : les variables
# d'environnement de production ne sont pas encore injectées. Ce drapeau
# NE lève que le garde-fou MinIO : collectstatic ne touche qu'aux
# fichiers statiques (whitenoise), jamais au stockage des justificatifs.
PHASE_BUILD = config("DJANGO_COLLECTSTATIC_BUILD", default=False, cast=bool)

ALLOWED_HOSTS = config("DJANGO_ALLOWED_HOSTS", default="", cast=Csv())

# En développement (DEBUG=True), on tolère des ALLOWED_HOSTS vides en
# fournissant des valeurs locales pratiques ; en production la variable
# d'environnement reste obligatoire.
if DEBUG and not ALLOWED_HOSTS:
    ALLOWED_HOSTS = ["localhost", "127.0.0.1"]

# En dev, autoriser automatiquement les adresses de la machine (accès
# depuis un appareil du même réseau, WebView Capacitor…) même quand la
# variable DJANGO_ALLOWED_HOSTS du .env est renseignée.
if DEBUG:
    try:
        import socket

        _, _, adresses = socket.gethostbyname_ex(socket.gethostname())
        ALLOWED_HOSTS += [a for a in adresses if not a.startswith("127.")]
    except OSError:
        pass


# ─────────────────────────────────────────────────────────────
# actif hors mode debug, càd en production
# https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/
# ─────────────────────────────────────────────────────────────
if not DEBUG:
    # Terminaison TLS gérée par un reverse-proxy (nginx, traefik…) :
    # Django doit savoir reconnaître une requête d'origine HTTPS via
    # l'en-tête transmis par le proxy.
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

    # Redirige tout le trafic HTTP vers HTTPS.
    SECURE_SSL_REDIRECT = config("DJANGO_SECURE_SSL_REDIRECT", default=True, cast=bool)

    # HSTS : force le navigateur à n'utiliser que HTTPS. Valeur par défaut
    # d'un an ; à n'activer qu'une fois le HTTPS confirmé stable.
    SECURE_HSTS_SECONDS = config("DJANGO_SECURE_HSTS_SECONDS", default=31536000, cast=int)
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

    # Cookies de session et CSRF uniquement transmis sur HTTPS.
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

    # Empêche le navigateur de deviner le type de contenu (anti-MIME-sniffing).
    SECURE_CONTENT_TYPE_NOSNIFF = True

    # Ne divulgue pas l'URL complète en Referer vers des sites externes.
    SECURE_REFERER_POLICY = "same-origin"

    # Origines de confiance pour la protection CSRF (schéma + hôte requis).
    CSRF_TRUSTED_ORIGINS = config(
        "DJANGO_CSRF_TRUSTED_ORIGINS", default="", cast=Csv()
    )


# ─────────────────────────────────────────────────────────────
# CORS : l'API est consommée par un frontend servi depuis une autre
# origine (SPA). On n'ouvre jamais tout par défaut :
#   - en production, seules les origines listées explicitement dans
#     DJANGO_CORS_ALLOWED_ORIGINS (schéma + hôte) sont autorisées ;
#   - en développement, on tolère les origines locales usuelles pour
#     ne pas bloquer le travail du frontend.
# ─────────────────────────────────────────────────────────────
CORS_ALLOWED_ORIGINS = config(
    "DJANGO_CORS_ALLOWED_ORIGINS", default="", cast=Csv()
)
if DEBUG and not CORS_ALLOWED_ORIGINS:
    CORS_ALLOWED_ORIGINS = [
        "http://localhost:3000",
        "http://127.0.0.1:3000",
        "http://localhost:5173",
        "http://127.0.0.1:5173",
        # WebView Capacitor (application mobile) : l'app mobile appelle l'API
        # depuis son origine embarquée https://localhost (Android).
        "http://localhost",
        "https://localhost",
    ]

# Autorise l'envoi des cookies / en-têtes d'authentification depuis le
# frontend (nécessaire pour les requêtes authentifiées cross-origin).
CORS_ALLOW_CREDENTIALS = True

# URL publique du frontend : utilisée pour construire les liens dans les
# emails transactionnels (connexion, correction de dossier…). En dev, le
# serveur Vite local ; en production, l'origine publique de la SPA.
FRONTEND_URL = config("FRONTEND_URL", default="http://localhost:5173").rstrip("/")

# Nombre de proxies inverses de confiance devant l'application. Sert au
# calcul de l'IP client depuis X-Forwarded-For (preuves légales de
# signature, journal d'audit) : on remonte depuis la DROITE du header,
# chaque saut correspondant à un proxy maîtrisé. 1 = un reverse proxy
# (nginx/traefik) devant Django ; 0 = exposition directe.
PROXIES_DE_CONFIANCE = config("PROXIES_DE_CONFIANCE", default=1, cast=int)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'comptes',
    'rest_framework_simplejwt.token_blacklist',
    'sgi',
    'dossiers',
    'audit',
    'notifications',
    'administration',
    'accueil',
    'drf_spectacular',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # WhiteNoise sert les fichiers statiques de Django en production
    # (le plus haut possible, juste après SecurityMiddleware).
    'whitenoise.middleware.WhiteNoiseMiddleware',
    # CorsMiddleware doit être placé le plus haut possible, et surtout
    # avant CommonMiddleware, pour pouvoir ajouter les en-têtes CORS aux
    # réponses (y compris les réponses d'erreur générées tôt).
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'pgnoc.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'pgnoc.wsgi.application'


# Database
# https://docs.djangoproject.com/6.0/ref/settings/#databases

# En développement local sans PostgreSQL, on bascule automatiquement
# sur SQLite :aucune installation externe nécessaire.
_POSTGRES_DB = config("POSTGRES_DB", default="")
if _POSTGRES_DB:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": _POSTGRES_DB,
            "USER": config("POSTGRES_USER"),
            "PASSWORD": config("POSTGRES_PASSWORD"),
            "HOST": config("POSTGRES_HOST", default="localhost"),
            "PORT": config("POSTGRES_PORT", default="5432"),
        }
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }



# MinIO (S3-compatible) pour les justificatifs. Si MINIO_ENDPOINT_URL est
# VIDE (développement local sans conteneur), on bascule automatiquement sur
# le système de fichiers local : l'API reste 100 % testable, notamment sur
# Swagger, et les URLs signées deviennent des URLs /media/ servies par Django.
# En production, renseigner l'endpoint pour activer MinIO.
MINIO_ENDPOINT_URL = config("MINIO_ENDPOINT_URL", default="")

if MINIO_ENDPOINT_URL:
    STORAGES = {
        "default": {"BACKEND": "storages.backends.s3boto3.S3Boto3Storage"},
        "staticfiles": {
            "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
        },
    }
else:
    STORAGES = {
        "default": {"BACKEND": "django.core.files.storage.FileSystemStorage"},
        "staticfiles": {
            "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
        },
    }

MEDIA_ROOT = BASE_DIR / "media"
MEDIA_URL = "/media/"

AWS_ACCESS_KEY_ID = config("MINIO_ACCESS_KEY", default="")
AWS_SECRET_ACCESS_KEY = config("MINIO_SECRET_KEY", default="")
AWS_STORAGE_BUCKET_NAME = config("MINIO_BUCKET_NAME", default="pgnoc-ti-documents")
AWS_S3_ENDPOINT_URL = MINIO_ENDPOINT_URL
# URL publique pour la génération des URLs signées (ex: https://minio.mondomaine.com
# ou http://localhost:9000 en dev). Si non défini, fallback sur MINIO_ENDPOINT_URL.
# Permet de générer des URLs signées accessibles depuis le navigateur
# même si MINIO_ENDPOINT_URL est un hostname interne (ex: minio:9000).
AWS_S3_CUSTOM_DOMAIN = config("MINIO_PUBLIC_URL", default=MINIO_ENDPOINT_URL)
AWS_S3_USE_SSL = config("MINIO_USE_SSL", default=False, cast=bool)
AWS_DEFAULT_ACL = None  # PAS de fichier public par défaut
AWS_QUERYSTRING_AUTH = True  # essentiel : force les URLs signées
AWS_QUERYSTRING_EXPIRE = 600  # URL valide 10 minutes seulement

# Garde-fou : hors DEBUG, MinIO est requis pour les justificatifs.
# En mode local (DEBUG=True), le FileSystemStorage sert les fichiers
# via /media/ mais les URLs ne sont ni signées ni expirantes.
# Exception : la phase de build Docker (collectstatic) n'a pas les
# variables de prod et ne touche pas au stockage média.
if not EXECUTION_TESTS and not PHASE_BUILD and not DEBUG and not MINIO_ENDPOINT_URL:
    raise RuntimeError(
        "MINIO_ENDPOINT_URL doit être renseigné en production. "
        "Les justificatifs KYC nécessitent un stockage S3 signé."
    )


# Hachage des mots de passe — exigence du cahier des charges (Argon2/PBKDF2).
# Argon2id est le hasher le plus robuste (résiste au GPC et au cracking GPU).
# PBKDF2 est conservé en deuxième position : les mots de passe déjà hachés
# en PBKDF2 continuent de fonctionner et sont migrés vers Argon2 à la
# prochaine connexion réussie (mise à niveau transparente de Django).
PASSWORD_HASHERS = [
    "django.contrib.auth.hashers.Argon2PasswordHasher",
    "django.contrib.auth.hashers.PBKDF2PasswordHasher",
    "django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher",
]


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'fr-fr'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
# Rassemblés par `collectstatic` (servis par WhiteNoise en production).
STATIC_ROOT = BASE_DIR / "staticfiles"
# Modèle utilisateur personnalisé (doit être défini AVANT la première migration)
AUTH_USER_MODEL = "comptes.Utilisateur"

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.IsAuthenticated",
    ),

    # Toute erreur (validation, 401/403/404, throttle, bug…) sort dans
    # une enveloppe unifiée {code, message, detail, champs} en français :
    # le frontend affiche `message` tel quel et branche sa logique sur
    # `code` (voir pgnoc/erreurs.py).
    "EXCEPTION_HANDLER": "pgnoc.erreurs.handler_erreurs",

    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",

    # Pagination par défaut : les listes (dossiers, valeurs de champs…)
    # peuvent grossir ; sans pagination une requête renverrait toute la
    # table d'un coup. Taille de page surchargeable par variable d'env.
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": config("DRF_PAGE_SIZE", default=25, cast=int),
    "PAGE_SIZE_QUERY_PARAM": "page_size",
    "MAX_PAGE_SIZE": 100,

    # Limitation de débit (throttling). On s'appuie sur ScopedRateThrottle :
    # seules les vues déclarant un `throttle_scope` sont limitées (login,
    # register…), les autres ne subissent aucune limite. Cela protège les
    # endpoints d'authentification publics contre le brute-force et les
    # inscriptions en masse. Les taux sont surchargeables par variable d'env.
    "DEFAULT_THROTTLE_CLASSES": (
        "rest_framework.throttling.ScopedRateThrottle",
    ),
    "DEFAULT_THROTTLE_RATES": {
        "connexion": config("DRF_THROTTLE_LOGIN", default="5/min"),
        "inscription": config("DRF_THROTTLE_REGISTER", default="10/hour"),
        "otp": config("DRF_THROTTLE_OTP", default="10/min"),
    },
}

SIMPLE_JWT = {
    # Access token à durée de vie courte : exigence de sécurité du
    # cahier des charges (section 8.1) — 60 minutes.
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=60),
    # Refresh token : 24 heures (cahier des charges section 8.1).
    "REFRESH_TOKEN_LIFETIME": timedelta(hours=24),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "UPDATE_LAST_LOGIN": True,
    "ALGORITHM": "HS256",
    # Clé de signature distincte de SECRET_KEY pour isoler les tokens JWT
    # des autres mécanismes (session, CSRF, HMAC preuves de vie).
    "SIGNING_KEY": config("DJANGO_SIGNING_KEY", default=SECRET_KEY),
    "AUTH_HEADER_TYPES": ("Bearer",),
    "USER_ID_FIELD": "id",
    "USER_ID_CLAIM": "user_id",
}


# ─────────────────────────────────────────────────────────────
# Celery — tâches asynchrones (notifications, emails, cache…).
# Le broker et le backend utilisent Redis. En dev local, le
# docker-compose lance Redis sur le port 6379.
# ─────────────────────────────────────────────────────────────
CELERY_BROKER_URL = config("CELERY_BROKER_URL", default="redis://localhost:6379/0")
CELERY_RESULT_BACKEND = config("CELERY_RESULT_BACKEND", default="redis://localhost:6379/0")
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = TIME_ZONE


# ─────────────────────────────────────────────────────────────
# Email — envoi transactionnel (UC02 inscription, etc.).
# En dev/debug, le backend console imprime les emails dans le
# terminal. En prod, utiliser EMAIL_BACKEND du .env (ex.
# django.core.mail.backends.smtp.EmailBackend).
# ─────────────────────────────────────────────────────────────
EMAIL_BACKEND = config(
    "EMAIL_BACKEND",
    default=(
        "django.core.mail.backends.console.EmailBackend"
        if DEBUG
        else "django.core.mail.backends.smtp.EmailBackend"
    ),
)
DEFAULT_FROM_EMAIL = config("DEFAULT_FROM_EMAIL", default="noreply@pgnoc-ti.local")
EMAIL_HOST = config("EMAIL_HOST", default="localhost")
EMAIL_PORT = config("EMAIL_PORT", default=587, cast=int)
EMAIL_USE_TLS = config("EMAIL_USE_TLS", default=True, cast=bool)
EMAIL_HOST_USER = config("EMAIL_HOST_USER", default="")
EMAIL_HOST_PASSWORD = config("EMAIL_HOST_PASSWORD", default="")


# ─────────────────────────────────────────────────────────────
# Google OAuth 2.0 (connexion « Se connecter avec Google », UC01).
# Le flux est 100 % côté backend : le navigateur redirige vers
# l'écran Google, Google rappelle le backend (callback), qui échange
# le code d'autorisation contre les tokens Google, récupère le
# profil (email, prénom, nom, google sub) puis délivre NOS propres
# tokens JWT au frontend. Le client_secret ne quitte jamais le serveur.
# ─────────────────────────────────────────────────────────────
GOOGLE_OAUTH_CLIENT_ID = config("GOOGLE_OAUTH_CLIENT_ID", default="")
GOOGLE_OAUTH_CLIENT_SECRET = config("GOOGLE_OAUTH_CLIENT_SECRET", default="")
# URL de callback déclarée dans la console Google Cloud (redirect URI
# autorisée). Doit correspondre EXACTEMENT au chemin du endpoint callback.
GOOGLE_OAUTH_CALLBACK_URL = config(
    "GOOGLE_OAUTH_CALLBACK_URL",
    default="http://localhost:8000/api/comptes/oauth/google/callback/",
)
# URL du frontend vers laquelle le navigateur est redirigé après
# l'authentification, avec les tokens JWT dans le fragment (#access=...).
# Le fragment n'est jamais envoyé au serveur (ni loggé) : bonne pratique.
GOOGLE_OAUTH_FRONT_REDIRECT = config(
    "GOOGLE_OAUTH_FRONT_REDIRECT", default="http://localhost:5173/oauth"
)


# ─────────────────────────────────────────────────────────────
# Journalisation applicative.
# Sans cette configuration, les `logger.exception()` des garde-fous
# best-effort (échec d'écriture du journal d'audit, échec d'envoi des
# notifications…) sont silencieux en production : la plateforme serait
# aveugle exactement là où elle doit être la plus bavarde.
#
# - `pgnoc.audit`       : échecs de traçabilité (exigence CREPMF) → WARNING mini,
#                         dupliqués dans un fichier dédié pour l'exploitation ;
# - `pgnoc`             : reste du code applicatif ;
# - `django.request`    : 4xx/5xx non interceptés.
# Le répertoire de logs est créé au démarrage ; il est désactivable
# (DJANGO_LOG_TO_FILE=False) pour les environnements conteneurisés qui
# collectent uniquement stdout.
# ─────────────────────────────────────────────────────────────
# Pendant la suite de tests, on n'écrit aucun fichier et on tait la
# console : plusieurs tests provoquent VOLONTAIREMENT des pannes
# (échec d'audit, notification impossible) et leurs traces rendraient
# la sortie de test illisible.
# En mode test, les tâches s'exécutent dans le processus (pas de broker requis).
CELERY_TASK_ALWAYS_EAGER = EXECUTION_TESTS


# ─────────────────────────────────────────────────────────────
# Cache Redis (§8.2 Performance) — formulaires KYC et données
# fréquemment accédées.
# En dev local sans Redis, le cache « locmem » évite les erreurs.
# ─────────────────────────────────────────────────────────────
_redis_url = config("REDIS_URL", default="redis://localhost:6379/1")
if EXECUTION_TESTS:
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        }
    }
else:
    import socket
    _redis_available = False
    try:
        _sock = socket.create_connection((_redis_url.split("://")[1].split(":")[0], 6379), timeout=1)
        _sock.close()
        _redis_available = True
    except OSError:
        pass
    if _redis_available:
        CACHES = {
            "default": {
                "BACKEND": "django.core.cache.backends.redis.RedisCache",
                "LOCATION": _redis_url,
                "KEY_PREFIX": "pgnoc",
                "TIMEOUT": 15 * 60,
            }
        }
    else:
        CACHES = {
            "default": {
                "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
            }
        }


# ─────────────────────────────────────────────────────────────
# Garde-fou : hors DEBUG, le moteur DOIT être PostgreSQL.
# SQLite ne supporte pas les triggers RunSQL, les verrous
# SELECT FOR UPDATE ni les transactions concurrentes.
# ─────────────────────────────────────────────────────────────
if not EXECUTION_TESTS and not DEBUG and "sqlite" in DATABASES["default"]["ENGINE"]:
    raise RuntimeError(
        "Le moteur de base de données doit être PostgreSQL en production. "
        "Configurer POSTGRES_DB, POSTGRES_USER, POSTGRES_PASSWORD, "
        "POSTGRES_HOST et POSTGRES_PORT."
    )

LOG_LEVEL = config("DJANGO_LOG_LEVEL", default="INFO" if not DEBUG else "DEBUG")
LOG_TO_FILE = config(
    "DJANGO_LOG_TO_FILE", default=not EXECUTION_TESTS, cast=bool
)
LOG_DIR = Path(config("DJANGO_LOG_DIR", default=str(BASE_DIR / "logs")))

_handlers_applicatifs = ["console"]
_handlers_audit = ["console"]

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbeux": {
            "format": "{asctime} [{levelname}] {name} {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "verbeux",
        },
    },
    "loggers": {
        "django.request": {
            "handlers": _handlers_applicatifs,
            "level": "WARNING",
            "propagate": False,
        },
        "pgnoc": {
            "handlers": _handlers_applicatifs,
            "level": LOG_LEVEL,
            "propagate": False,
        },
        "pgnoc.audit": {
            "handlers": _handlers_audit,
            # Un échec de journalisation est toujours notable, quel que
            # soit le niveau global choisi pour le reste de l'application.
            "level": "WARNING",
            "propagate": False,
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "WARNING",
    },
}

if LOG_TO_FILE:
    LOG_DIR.mkdir(parents=True, exist_ok=True)
    LOGGING["handlers"]["fichier_application"] = {
        "class": "logging.handlers.RotatingFileHandler",
        "filename": str(LOG_DIR / "application.log"),
        "maxBytes": 5 * 1024 * 1024,
        "backupCount": 5,
        "formatter": "verbeux",
        "encoding": "utf-8",
    }
    # Fichier séparé pour l'audit : il ne doit pas être noyé dans le
    # bruit applicatif, c'est la piste d'alerte de conformité.
    LOGGING["handlers"]["fichier_audit"] = {
        "class": "logging.handlers.RotatingFileHandler",
        "filename": str(LOG_DIR / "audit.log"),
        "maxBytes": 5 * 1024 * 1024,
        "backupCount": 10,
        "formatter": "verbeux",
        "encoding": "utf-8",
    }
    _handlers_applicatifs.append("fichier_application")
    _handlers_audit.append("fichier_audit")

if EXECUTION_TESTS:
    for _configuration in LOGGING["loggers"].values():
        _configuration["level"] = "CRITICAL"
    LOGGING["root"]["level"] = "CRITICAL"


SPECTACULAR_SETTINGS = {
    "TITLE": "PGNOC-TI API",
    "DESCRIPTION": (
        "Plateforme de Gestion Numérique d'Ouverture de Comptes-Titres "
        "pour Investisseurs."
    ),
    "VERSION": "1.0.0",
    # Empêche l'auto-inclusion du schéma /api/schema/ lui-même dans
    # la doc générée (bruit inutile).
    "SERVE_INCLUDE_SCHEMA": False,
    # Documente explicitement le schéma d'authentification Bearer JWT,
    # sinon Swagger UI ne propose pas le bouton "Authorize" correctement.
    "SWAGGER_UI_SETTINGS": {
        "persistAuthorization": True,
    },
    # Regroupe les endpoints par app plutôt que par ordre alphabétique
    # brut, pour une navigation plus lisible (comptes, sgi, etc.).
    "COMPONENT_SPLIT_REQUEST": True,
}