# Generated by Django 6.0.6 on 2026-07-29 19:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sgi', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EtapeKYC',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant')),
                ('nom', models.CharField(max_length=255, verbose_name="Nom de l'étape")),
                ('ordre', models.PositiveIntegerField(default=0, help_text="Détermine la position de l'étape dans le parcours.", verbose_name='Ordre')),
                ('actif', models.BooleanField(default=True, help_text='Seule une étape active est proposée aux nouveaux dossiers.', verbose_name='Actif')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('sgi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapes_kyc', to='sgi.sgi', verbose_name='SGI propriétaire')),
            ],
            options={
                'verbose_name': 'Étape KYC',
                'verbose_name_plural': 'Étapes KYC',
                'ordering': ['sgi', 'ordre'],
            },
        ),
        migrations.CreateModel(
            name='Dossier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant')),
                ('reference', models.CharField(editable=False, help_text='Référence humaine générée automatiquement (ex: PGNOC-2026-000123).', max_length=30, unique=True, verbose_name='Référence')),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('SOUMIS', 'Soumis'), ('EN_INSTRUCTION', 'En instruction'), ('VALIDE', 'Validé'), ('REJETE', 'Rejeté')], db_index=True, default='BROUILLON', max_length=20, verbose_name='Statut')),
                ('version', models.PositiveIntegerField(default=1, help_text='Incrémentée à chaque nouvelle soumission après un rejet/correction.', verbose_name='Version')),
                ('progression_pct', models.PositiveSmallIntegerField(default=0, help_text='Pourcentage de champs obligatoires renseignés, calculé applicativement.', verbose_name='Progression (%)')),
                ('motif_rejet', models.TextField(blank=True, verbose_name='Motif de rejet')),
                ('type_signature', models.CharField(blank=True, choices=[('OTP', 'OTP'), ('BIOMETRIQUE', 'Biométrique')], max_length=25, verbose_name='Type de signature')),
                ('donnee_signature', models.TextField(blank=True, help_text='Référence opaque à la preuve de signature (ex: identifiant de transaction OTP, hash du document signé). Ne stocke jamais de données biométriques brutes.', verbose_name='Donnée de signature')),
                ('date_signature', models.DateTimeField(blank=True, null=True, verbose_name='Date de signature')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_soumission', models.DateTimeField(blank=True, null=True, verbose_name='Date de soumission')),
                ('date_instruction', models.DateTimeField(blank=True, null=True, verbose_name='Date de prise en instruction')),
                ('date_decision', models.DateTimeField(blank=True, null=True, verbose_name='Date de décision')),
                ('agent', models.ForeignKey(blank=True, help_text="Renseigné quand un Agent SGI prend en charge le dossier (transition SOUMIS → EN_INSTRUCTION). Nommer le champ `agent` (plutôt que `agent_id`) est la convention Django idiomatique : le framework crée automatiquement la colonne SQL `agent_id`, identique à celle du document de conception — `dossier.agent` donne l'objet Utilisateur, `dossier.agent_id` donne directement l'UUID sans requête supplémentaire.", limit_choices_to={'role__code': 'AGENT_SGI'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dossiers_instruits', to=settings.AUTH_USER_MODEL, verbose_name='Agent en charge')),
                ('sgi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dossiers', to='sgi.sgi', verbose_name='SGI destinataire')),
                ('utilisateur', models.ForeignKey(limit_choices_to={'role__code': 'INVESTISSEUR'}, on_delete=django.db.models.deletion.PROTECT, related_name='dossiers', to=settings.AUTH_USER_MODEL, verbose_name='Investisseur')),
                ('etape_courante', models.ForeignKey(blank=True, help_text="Étape à laquelle en est l'investisseur pendant la saisie (statut BROUILLON).", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dossiers_en_cours', to='dossiers.etapekyc', verbose_name='Étape courante')),
            ],
            options={
                'verbose_name': 'Dossier',
                'verbose_name_plural': 'Dossiers',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='ChampKYC',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant')),
                ('code', models.SlugField(help_text='Généré automatiquement depuis le nom si non fourni. Clé stable utilisée par ValeurChamp — ne doit jamais changer après création.', max_length=100, verbose_name='Code technique')),
                ('nom', models.CharField(max_length=255, verbose_name='Nom affiché')),
                ('type', models.CharField(choices=[('TEXTE_COURT', 'Texte court'), ('TEXTE_LONG', 'Texte long'), ('NOMBRE', 'Nombre'), ('DATE', 'Date'), ('BOOLEEN', 'Case à cocher'), ('CHOIX_UNIQUE', 'Choix unique'), ('CHOIX_MULTIPLE', 'Choix multiple'), ('FICHIER', 'Fichier joint')], max_length=20, verbose_name='Type de champ')),
                ('obligatoire', models.BooleanField(default=True, verbose_name='Obligatoire')),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('justification', models.TextField(blank=True, help_text="Explique à l'investisseur pourquoi cette information est demandée.", verbose_name='Justification')),
                ('options_choix', models.JSONField(blank=True, help_text='Liste de chaînes, ex: ["Salarié", "Indépendant", "Retraité"].', null=True, verbose_name='Options (CHOIX_UNIQUE / CHOIX_MULTIPLE)')),
                ('valeur_declencheur', models.CharField(blank=True, help_text="Valeur du champ parent qui déclenche l'affichage de ce champ.", max_length=255, verbose_name='Valeur déclencheur')),
                ('formats_acceptes', models.CharField(blank=True, help_text="Ex: 'pdf,jpg,png'. Utilisé uniquement pour le type FICHIER.", max_length=255, verbose_name='Formats de fichiers acceptés')),
                ('taille_max_mo', models.PositiveIntegerField(blank=True, help_text='Utilisé uniquement pour le type FICHIER.', null=True, verbose_name='Taille maximale (Mo)')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('champ_parent', models.ForeignKey(blank=True, help_text="Si renseigné, ce champ ne s'affiche que si `champ_parent` a pour valeur `valeur_declencheur`.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='champs_enfants', to='dossiers.champkyc', verbose_name="Champ parent (condition d'affichage)")),
                ('etape', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='champs', to='dossiers.etapekyc', verbose_name='Étape KYC')),
            ],
            options={
                'verbose_name': 'Champ KYC',
                'verbose_name_plural': 'Champs KYC',
                'ordering': ['etape', 'ordre'],
            },
        ),
        migrations.CreateModel(
            name='ValeurChamp',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant')),
                ('valeur', models.TextField(blank=True, help_text='Valeur textuelle brute. Pour CHOIX_MULTIPLE, stockée en JSON sérialisé (ex: \'["Salarié", "Retraité"]\').', verbose_name='Valeur')),
                ('fichier', models.CharField(blank=True, help_text="Clé/chemin de l'objet sur MinIO (pas l'URL signée, qui est temporaire et générée à la demande — Étape 2.4).", max_length=500, verbose_name='Référence fichier')),
                ('commentaire_agent', models.TextField(blank=True, help_text="Renseigné par un Agent SGI lors d'une demande de correction (UC09).", verbose_name="Commentaire de l'agent")),
                ('est_corrige', models.BooleanField(default=False, help_text="Passe à True quand l'investisseur ressaisit ce champ après un commentaire_agent, pour signaler à l'agent que la correction attend une nouvelle relecture.", verbose_name='Corrigé')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_maj', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('champ', models.ForeignKey(help_text="PROTECT plutôt que CASCADE : on ne veut jamais qu'une suppression de champ efface silencieusement des réponses déjà soumises par un investisseur (traçabilité).", on_delete=django.db.models.deletion.PROTECT, related_name='valeurs', to='dossiers.champkyc', verbose_name='Champ KYC')),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valeurs_champs', to='dossiers.dossier', verbose_name='Dossier')),
            ],
            options={
                'verbose_name': 'Valeur de champ',
                'verbose_name_plural': 'Valeurs de champs',
                'ordering': ['dossier', 'champ__ordre'],
            },
        ),
        migrations.AddConstraint(
            model_name='etapekyc',
            constraint=models.UniqueConstraint(fields=('sgi', 'ordre'), name='unique_ordre_par_sgi'),
        ),
        migrations.AddIndex(
            model_name='dossier',
            index=models.Index(fields=['sgi', 'statut'], name='dossiers_do_sgi_id_78f026_idx'),
        ),
        migrations.AddConstraint(
            model_name='champkyc',
            constraint=models.UniqueConstraint(fields=('etape', 'code'), name='unique_code_par_etape'),
        ),
        migrations.AddConstraint(
            model_name='valeurchamp',
            constraint=models.UniqueConstraint(fields=('dossier', 'champ'), name='unique_valeur_par_dossier_et_champ'),
        ),
    ]
