# Generated by Django 6.0.6 on 2026-08-10 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dossiers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dossier',
            name='convention_acceptee',
            field=models.BooleanField(default=False, help_text="Engagement irréversible de l'investisseur : requis pour soumettre le dossier dès lors que la SGI a publié sa convention tarifaire (UC16).", verbose_name='Convention tarifaire acceptée'),
        ),
    ]
