# Generated by Django 6.0.6 on 2026-08-10 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dossiers', '0002_dossier_convention_acceptee'),
    ]

    operations = [
        migrations.AddField(
            model_name='dossier',
            name='ip_signature',
            field=models.GenericIPAddressField(blank=True, help_text='IP du client au moment de la signature (preuve légale).', null=True, verbose_name='Adresse IP de signature'),
        ),
        migrations.AddField(
            model_name='dossier',
            name='otp_expiration',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Expiration du code OTP'),
        ),
        migrations.AddField(
            model_name='dossier',
            name='otp_hash',
            field=models.CharField(blank=True, help_text='Empreinte PBKDF2 du code OTP en attente de vérification. Jamais le code en clair ; purgée dès la signature posée.', max_length=128, verbose_name='Hash du code OTP'),
        ),
    ]
