# Generated by Django 6.0.6 on 2026-08-16 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dossiers', '0003_dossier_ip_signature_dossier_otp_expiration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='valeurchamp',
            name='date_capture',
            field=models.DateTimeField(blank=True, help_text='Horodatage serveur de la réception du selfie.', null=True, verbose_name='Date de capture'),
        ),
        migrations.AddField(
            model_name='valeurchamp',
            name='empreinte_sha256',
            field=models.CharField(blank=True, help_text="Hash du contenu stocké, calculé côté serveur à l'upload (champs SELFIE).", max_length=64, verbose_name='Empreinte SHA-256 du fichier'),
        ),
        migrations.AddField(
            model_name='valeurchamp',
            name='signature_serveur',
            field=models.CharField(blank=True, help_text="HMAC-SHA256 de (référence, valeur, chemin, empreinte, horodatage) signée avec une clé serveur dédiée — vérifie que l'enregistrement n'a pas été altéré après l'upload.", max_length=128, verbose_name='Signature HMAC serveur'),
        ),
        migrations.AlterField(
            model_name='champkyc',
            name='type',
            field=models.CharField(choices=[('TEXTE_COURT', 'Texte court'), ('TEXTE_LONG', 'Texte long'), ('NOMBRE', 'Nombre'), ('DATE', 'Date'), ('BOOLEEN', 'Case à cocher'), ('CHOIX_UNIQUE', 'Choix unique'), ('CHOIX_MULTIPLE', 'Choix multiple'), ('FICHIER', 'Fichier joint'), ('SELFIE', 'Selfie de vérification')], max_length=20, verbose_name='Type de champ'),
        ),
    ]
