# Generated by Django 6.0.6 on 2026-09-04 12:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dossiers', '0004_preuve_vie_selfie'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='dossier',
            name='agent',
            field=models.ForeignKey(blank=True, help_text='Renseigné quand un Agent SGI ou Admin SGI prend en charge le dossier (transition SOUMIS → EN_INSTRUCTION).', limit_choices_to={'role__code__in': ['AGENT_SGI', 'ADMIN_SGI']}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dossiers_instruits', to=settings.AUTH_USER_MODEL, verbose_name='Agent en charge'),
        ),
    ]
