# Generated by Django 6.0.6 on 2026-09-08 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dossiers', '0005_alter_dossier_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='dossier',
            name='convention_version',
            field=models.CharField(blank=True, editable=False, help_text="Empreinte (nom de stockage) du PDF de convention au moment de l'acceptation. Si la SGI publie une nouvelle convention, cette empreinte ne correspond plus à la version courante et l'acceptation doit être renouvelée : l'investisseur ne peut être engagé que par un document qu'il a réellement vu.", max_length=300, verbose_name='Version de la convention acceptée'),
        ),
        migrations.AddField(
            model_name='dossier',
            name='otp_tentatives',
            field=models.PositiveSmallIntegerField(default=0, editable=False, help_text="Compteur de codes erronés depuis la dernière génération ; au-delà du plafond, l'OTP est purgé (anti brute-force).", verbose_name='Tentatives OTP erronées'),
        ),
    ]
