# Generated by Django 6.0.6 on 2026-09-09 01:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dossiers', '0006_dossier_convention_version_dossier_otp_tentatives'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dossier',
            name='statut',
            field=models.CharField(choices=[('BROUILLON', 'Brouillon'), ('SOUMIS', 'Soumis'), ('EN_INSTRUCTION', 'En instruction'), ('VALIDE', 'Validé'), ('REJETE', 'Rejeté'), ('ACTIF', 'Compte actif')], db_index=True, default='BROUILLON', max_length=20, verbose_name='Statut'),
        ),
        migrations.CreateModel(
            name='DepotMinimum',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant')),
                ('montant_requis', models.DecimalField(decimal_places=0, default=0, max_digits=14, verbose_name='Montant requis (FCFA)')),
                ('instructions', models.TextField(blank=True, verbose_name='Instructions de paiement')),
                ('methodes_acceptees', models.JSONField(default=list, verbose_name='Méthodes acceptées')),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('PREUVE_DEPOSEE', 'Preuve déposée'), ('APPROUVE', 'Approuvé'), ('REJETE', 'Rejeté')], db_index=True, default='EN_ATTENTE', max_length=20, verbose_name='Statut')),
                ('montant_depose', models.DecimalField(blank=True, decimal_places=0, max_digits=14, null=True, verbose_name='Montant déposé (FCFA)')),
                ('methode_paiement', models.CharField(blank=True, max_length=30, verbose_name='Méthode de paiement')),
                ('reference_transaction', models.CharField(blank=True, max_length=100, verbose_name='Référence de la transaction')),
                ('preuve', models.FileField(blank=True, help_text="Capture d'écran (image) ou relevé PDF de la transaction.", upload_to='dossiers/depots/', verbose_name='Preuve de dépôt')),
                ('date_depot', models.DateTimeField(blank=True, null=True, verbose_name='Date de dépôt')),
                ('commentaire_agent', models.TextField(blank=True, verbose_name='Commentaire de la SGI')),
                ('date_verification', models.DateTimeField(blank=True, null=True, verbose_name='Date de vérification')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_maj', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('dossier', models.OneToOneField(help_text='Un dépôt par dossier : créé à la validation du dossier (post-validation).', on_delete=django.db.models.deletion.CASCADE, related_name='depot_minimum', to='dossiers.dossier', verbose_name='Dossier')),
            ],
            options={
                'verbose_name': 'Dépôt minimum',
                'verbose_name_plural': 'Dépôts minimum',
            },
        ),
    ]
