# Generated by Django 6.0.6 on 2026-08-10 10:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalAudit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant')),
                ('action', models.CharField(choices=[('CONNEXION', 'Connexion'), ('INSCRIPTION', 'Inscription'), ('CREATION_DOSSIER', 'Création de dossier'), ('TRANSITION_DOSSIER', 'Transition de statut de dossier'), ('COMMENTAIRE_AGENT', "Commentaire d'un agent")], db_index=True, max_length=30, verbose_name='Action')),
                ('entite_concernee', models.CharField(help_text="Nom de l'entité métier, ex: 'Dossier', 'Utilisateur', 'ValeurChamp'.", max_length=100, verbose_name='Entité concernée')),
                ('entite_id', models.CharField(db_index=True, max_length=100, verbose_name="Identifiant de l'entité")),
                ('avant', models.JSONField(blank=True, help_text="État précédent de l'entité (JSONB dans le MLD).", null=True, verbose_name='État avant')),
                ('apres', models.JSONField(blank=True, help_text="Nouvel état de l'entité (JSONB dans le MLD).", null=True, verbose_name='État après')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
                ('user_agent', models.CharField(blank=True, max_length=500, verbose_name='User-Agent')),
                ('date_action', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Date de l'action")),
                ('utilisateur', models.ForeignKey(blank=True, help_text="Null seulement si l'action n'est pas imputable à un compte utilisateur identifié (ex: tentative de connexion échouée).", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='traces_audit', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': "Entrée d'audit",
                'verbose_name_plural': "Journal d'audit",
                'ordering': ['-date_action'],
                'indexes': [models.Index(fields=['entite_concernee', 'entite_id'], name='audit_journ_entite__176cf3_idx')],
            },
        ),
    ]
