# Generated by Django 6.0.6 on 2026-08-14 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_verrou_insert_only'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalaudit',
            name='action',
            field=models.CharField(choices=[('CONNEXION', 'Connexion'), ('INSCRIPTION', 'Inscription'), ('CREATION_DOSSIER', 'Création de dossier'), ('TRANSITION_DOSSIER', 'Transition de statut de dossier'), ('COMMENTAIRE_AGENT', "Commentaire d'un agent"), ('ACCEPTATION_CONVENTION', 'Acceptation de la convention tarifaire'), ('POSE_SIGNATURE', 'Signature électronique posée'), ('CREATION_AGENT', "Création d'un agent SGI"), ('MODIFICATION_AGENT', "Modification d'un agent SGI"), ('MODIFICATION_CONVENTION', 'Publication de la convention tarifaire'), ('MODIFICATION_PRESENTATION', 'Publication de la présentation'), ('CREATION_ETAPE_KYC', "Création d'une étape KYC"), ('MODIFICATION_ETAPE_KYC', "Modification d'une étape KYC"), ('SUPPRESSION_ETAPE_KYC', "Suppression d'une étape KYC"), ('CREATION_CHAMP_KYC', "Création d'un champ KYC"), ('MODIFICATION_CHAMP_KYC', "Modification d'un champ KYC"), ('SUPPRESSION_CHAMP_KYC', "Suppression d'un champ KYC"), ('CREATION_SGI', "Création d'une SGI partenaire"), ('MODIFICATION_SGI', "Modification d'une SGI partenaire"), ('CREATION_UTILISATEUR', "Création d'un compte interne"), ('MODIFICATION_UTILISATEUR', "Modification d'un compte interne")], db_index=True, max_length=30, verbose_name='Action'),
        ),
    ]
