# Generated by Django 6.0.6 on 2026-07-21 15:56

import comptes.managers
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant')),
                ('email', models.EmailField(db_index=True, error_messages={'unique': 'Un utilisateur avec cette adresse email existe déjà.'}, max_length=254, unique=True, verbose_name='Adresse email')),
                ('prenom', models.CharField(blank=True, max_length=150, verbose_name='Prénom')),
                ('nom', models.CharField(blank=True, max_length=150, verbose_name='Nom')),
                ('role', models.CharField(choices=[('INVESTISSEUR', 'Investisseur'), ('AGENT_SGI', 'Agent SGI'), ('ADMIN_SGI', 'Admin SGI'), ('ADMIN_GENERAL', 'Admin Général')], db_index=True, default='INVESTISSEUR', help_text="Rôle RBAC déterminant les permissions de l'utilisateur.", max_length=20, verbose_name='Rôle')),
                ('is_active', models.BooleanField(default=True, help_text='Indique si ce compte doit être traité comme actif. Décochez plutôt que de supprimer un compte.', verbose_name='Actif')),
                ('is_staff', models.BooleanField(default=False, help_text="Indique si l'utilisateur peut se connecter au Django Admin.", verbose_name='Statut équipe')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name="Date d'inscription")),
                ('date_maj', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
                'ordering': ['-date_joined'],
            },
            managers=[
                ('objects', comptes.managers.UtilisateurManager()),
            ],
        ),
    ]
