# Generated by Django 6.0.6 on 2026-07-22 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0001_initial'),
        ('sgi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='sgi',
            field=models.ForeignKey(blank=True, help_text='Obligatoire pour AGENT_SGI et ADMIN_SGI. Toujours NULL pour INVESTISSEUR (qui choisit sa SGI par dossier, pas par compte) et pour ADMIN_GENERAL (accès transversal).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='personnel', to='sgi.sgi', verbose_name='SGI de rattachement'),
        ),
    ]
