# Generated by Django 6.0.6 on 2026-07-22 13:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0002_utilisateur_sgi'),
        ('sgi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant')),
                ('code', models.CharField(choices=[('INVESTISSEUR', 'Investisseur'), ('AGENT_SGI', 'Agent SGI'), ('ADMIN_SGI', 'Admin SGI'), ('ADMIN_GENERAL', 'Admin Général')], db_index=True, max_length=20, unique=True, verbose_name='Code')),
                ('libelle', models.CharField(max_length=100, verbose_name='Libellé')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Rôle',
                'verbose_name_plural': 'Rôles',
                'ordering': ['code'],
            },
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Actif'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='Statut équipe'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='sgi',
            field=models.ForeignKey(blank=True, help_text='Obligatoire pour les rôles AGENT_SGI et ADMIN_SGI. Toujours NULL pour INVESTISSEUR et ADMIN_GENERAL.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='utilisateurs', to='sgi.sgi', verbose_name='SGI de rattachement'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='role',
            field=models.ForeignKey(help_text="Détermine les permissions RBAC de l'utilisateur.", on_delete=django.db.models.deletion.PROTECT, related_name='utilisateurs', to='comptes.role', verbose_name='Rôle'),
        ),
    ]
