# Generated by Django 6.0.6 on 2026-07-22 18:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0003_role_alter_utilisateur_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfilAdminGeneral',
            fields=[
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profil_admin_general', serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
                ('notes_internes', models.TextField(blank=True, help_text='Notes de supervision, non visibles par les autres rôles.', verbose_name='Notes internes')),
            ],
            options={
                'verbose_name': 'Profil Admin Général',
                'verbose_name_plural': 'Profils Admin Général',
            },
        ),
        migrations.CreateModel(
            name='ProfilAdminSGI',
            fields=[
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profil_admin_sgi', serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
                ('fonction', models.CharField(blank=True, help_text='Ex: Responsable Conformité, Directeur des Opérations.', max_length=100, verbose_name='Fonction')),
            ],
            options={
                'verbose_name': 'Profil Admin SGI',
                'verbose_name_plural': 'Profils Admin SGI',
            },
        ),
        migrations.CreateModel(
            name='ProfilAgentSGI',
            fields=[
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profil_agent_sgi', serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
                ('matricule', models.CharField(blank=True, help_text='Identifiant interne attribué par la SGI (facultatif).', max_length=50, verbose_name='Matricule interne')),
            ],
            options={
                'verbose_name': 'Profil Agent SGI',
                'verbose_name_plural': 'Profils Agent SGI',
            },
        ),
        migrations.CreateModel(
            name='ProfilInvestisseur',
            fields=[
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profil_investisseur', serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
                ('type_personne', models.CharField(choices=[('PHYSIQUE', 'Personne physique'), ('MORALE', 'Personne morale'), ('MINEUR', 'Mineur')], default='PHYSIQUE', max_length=20, verbose_name='Type de personne')),
                ('google_id', models.CharField(blank=True, help_text="Renseigné uniquement si l'inscription s'est faite via OAuth Google.", max_length=255, null=True, unique=True, verbose_name='Identifiant Google')),
            ],
            options={
                'verbose_name': 'Profil Investisseur',
                'verbose_name_plural': 'Profils Investisseur',
            },
        ),
    ]
