# Generated by Django 6.0.6 on 2026-09-04 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0006_verrou_coherence_role_sgi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='libelle',
            field=models.CharField(max_length=100, unique=True, verbose_name='Libellé'),
        ),
    ]
