# Generated by Django 6.0.6 on 2026-08-10 14:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant')),
                ('titre', models.CharField(max_length=255, verbose_name='Titre')),
                ('message', models.TextField(verbose_name='Message')),
                ('lue', models.BooleanField(db_index=True, default=False, verbose_name='Lue')),
                ('type_notif', models.CharField(choices=[('DOSSIER', 'Dossier'), ('SYSTEME', 'Système')], default='DOSSIER', max_length=20, verbose_name='Type')),
                ('date_creation', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date de création')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Destinataire')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-date_creation'],
            },
        ),
    ]
